name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [ "master" ] # ou "main", conforme seu repositório

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Blazor app
        run: dotnet publish -c Release -o release

      - name: Change base href to repository name
        run: |
          sed -i 's|<base href="/"|<base href="/REPOSITORY-NAME/"|' release/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
